version: 0.1

environment_variables:
  plaintext:
    FOO: "bar"

phases:
  install:
    commands:
      - cat /etc/os-release
      - uname -a
      - pwd
      - docker images
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - bundle exec rake db:create db:migrate
      - bundle exec rake
  post_build:
    commands:
      - echo Build completed on `date`
