# More info: http://ufoships.com/docs/ufo-settings/
image: tongueroo/hi
# clean_keep: 30
# ecr_keep: 30

# aws_profile_ufo_env_map:
#   default: staging
#   # More examples:
#   aws_profile1: production
#   aws_profile2: staging
#   aws_profile3: development

# ufo_env_cluster_map:
#   default: prod
#   # More examples:
#   production: prod
#   staging: stag
#   development: dev
